@startuml
title Una moto atraviesa la grilla sin obstáculos y la cantidad de movimientos es X.
":gpsChallenge" -> ":jugador" : mover()
loop mientras no se haya ganado
":jugador" -> ":moto" : mover(posicion Posicion)
":moto"-> ":mapa" : mover(posicion Posicion)
":mapa"-> ":llegada" : chequearVictoria(posicion Posicion)
alt se gana el juego
return true
":mapa"-> ":gpsChallenge" : terminarPartida()
end
":llegada"-> ":mapa" : false
end
@enduml