@startuml
title "cuatroPorCuatroEncuentraPozoNoEsPenalizada"

actor usuario
usuario -> "mapa : Mapa" : guaradarObstaculo(posicio : Posicion, pozo : Obstaculo)
usuario -> "cpc:Vehiculo" : mover(mapa : Mapa , derecha : Direccion)
"cpc:Vehiculo" -> "derecha : Direccion" :calcularPosicionSiguiente(posicion : Posicion)
return posicion
"cpc:Vehiculo" -> "mapa : Mapa" : atravesarObstaculo("cpc:Vehiculo")
"mapa : Mapa" -> "moto:Vehiculo" : getPosicion()
return "posicion"
"mapa : Mapa" -> "mapa : Mapa" : get( posicion : Posicion)
return pozo : Obstaculo
"mapa : Mapa" -> "pozo : Obstaculo" : penalizarMovimiento( cpc: Vehiculo)
"pozo : Obstaculo" -> "cpc:Vehiculo" : atravesarPozo()
"cpc:Vehiculo" -> "derecha : Direccion" : calcularPosicionSiguiente ()
return posicion
usuario -> "derecha : Direccion" : getMovimientos(posicion : Posicion)
return "movimientos"
@enduml