@startuml
title "Vehiculo se mueve a la derecha y encuentra sorpresa de cambio de vehiculo"
actor Actor

Actor -> "juego : Juego" : moverVehiculo(new Derecha())
"juego : Juego" -> "jugador : Jugador" : moverVehiculo(derecha)
"jugador : Jugador" -> "vehiculo : Vehiculo" : mover(derecha)
"vehiculo : Vehiculo" -> "mapa : Mapa" : moverVehiculo(vehiculo : Vehiculo, derecha : Derecha)
"mapa : Mapa" -> "derecha : Derecha" : calcularPosicionSiguiente(posicionDelVehiculo : Posicion)
"mapa : Mapa" -> "mapa : Mapa" : calles.get(posicionDelVehiculo)
alt not posicionDelVehiculo.estaEnLimites(anchoMapa, this.altoMapa)
"mapa : Mapa" -> "derecha : Derecha" : opuesto()
"derecha : Derecha" --> "mapa : Mapa" : new Izquierda()
"mapa : Mapa" -> "izquierda : Izquierda" : calcularPosicionSiguiente(posicionDelVehiculo)
"mapa : Mapa" --> "vehiculo : Vehiculo" : return
end
"mapa : Mapa" -> "vehiculo : Vehiculo" : aumentarMovimientos(1)
"mapa : Mapa" -> "calle : Calle" : atravesarCalle(vehiculo: Vehiculo)
"calle : Calle" -> "sorpresa : SorpresaCambioVehiculo" : interactuarConVehiculo(vehiculo)
"sorpresa : SorpresaCambioVehiculo" -> "vehiculo : Vehiculo" : atravesarSorpresaCambioVehiculo()
alt tipo == Moto()
"vehiculo : Vehiculo" -> "moto : Moto" : this.tipo = atravesarCambioVehiculo()
"moto : Moto" --> "vehiculo : Vehiculo" : new Auto()
end
"mapa : Mapa" -> "derecha : Derecha" : calcularPosicionSiguiente(posicionDelVehiculo)
@enduml
